
-- FFI library
ffi = require('ffi')
local C = ffi.C

-- Do not clear the DB with rules; we had it prepared by a different process.
assert(C.kr_rules_init(nil, 0, false) == 0)

-- hostname
hostname('c1ad6c7aa652')


-- LOGGING section ----------------------------------

-- logging.level
log_level('info')

-- logging.target
log_target('stdout')


-- MONITORING section -------------------------------
--- control socket location
local ffi = require('ffi')
local id = os.getenv('SYSTEMD_INSTANCE')
if not id then
	log_error(ffi.C.LOG_GRP_SYSTEM, 'environment variable $SYSTEMD_INSTANCE not set, which should not have been possible due to running under manager')
else
	-- Bind to control socket in CWD (= rundir in config)
    -- FIXME replace with relative path after fixing https://gitlab.nic.cz/knot/knot-resolver/-/issues/720
	local path = '/run/knot-resolver/control/'..id
    log_warn(ffi.C.LOG_GRP_SYSTEM, 'path = ' .. path)
	local ok, err = pcall(net.listen, path, nil, { kind = 'control' })
	if not ok then
		log_warn(ffi.C.LOG_GRP_NETWORK, 'bind to '..path..' failed '..err)
	end
end


--- function used for statistics collection
function collect_lazy_statistics()
	if stats == nil then
		modules.load('stats')
	end

	return stats.list()
end

--- function used for statistics collection
function collect_statistics()
	return stats.list()
end
-- OPTIONS section ----------------------------------

-- options.glue-checking
mode('normal')




-- options.query-priming
modules.load('priming')

-- options.time-jump-detection
modules.load('detect_time_jump')

-- options.refuse-no-rd
modules.load('refuse_nord')

-- options.qname-minimisation
option('NO_MINIMIZE', false)

-- options.query-loopback
option('ALLOW_LOCAL', false)

-- options.reorder-rrset
option('REORDER_RR', true)

-- options.query-case-randomization
option('NO_0X20', false)
-- NETWORK section ----------------------------------

-- network.do-ipv4/6
net.ipv4 = true
net.ipv6 = true



-- network.tcp-pipeline
net.tcp_pipeline(100)

-- network.edns-keep-alive
modules.load('edns_keepalive')

-- network.edns-buffer-size
net.bufsize(
    1232,
    1232
)




-- network.tls.padding
net.tls_padding(true)

-- network.quic.max_conns
net.quic_max_conns(1024)

-- network.quic.max_streams
net.quic_max_streams(1024)

-- network.quic.require_retry
net.quic_require_retry(false)



net.proxy_allowed({})

-- network.listen
net.listen(net['lo'],53,{kind='dns',freebind=false})

net.listen(net['lo'],853,{kind='tls',freebind=false})

net.listen(net['lo'],443,{kind='doh2',freebind=false})


-- DNSSEC section -----------------------------------


-- dnssec.logging-bogus
-- modules.unload('bogus_log')

-- dnssec.sentinel
modules.load('ta_sentinel')

-- dnssec.signal-query
modules.load('ta_signal_query')





-- FORWARD and FALLBACK section ----------------------------------




-- CACHE section ------------------------------------
cache.open(104857600, 'lmdb:///var/cache/knot-resolver')
cache.min_ttl(5)
cache.max_ttl(86400)
cache.ns_tout(1000)




-- DNS64 section ------------------------------------


-- Disable DNS64 by unloading module
-- modules.unload('dns64')


-- RATE-LIMITING section ------------------------------------


-- DEFER section ------------------------------------

assert(C.defer_init(
	'/run/knot-resolver/defer',
	0,
	2) == 0)


-- LUA section --------------------------------------
-- Custom Lua code cannot be validated


