server:
    interface: 0.0.0.0
    port: 53
    access-control: 0.0.0.0/0 allow
    do-daemonize: no
    verbosity: 1
    use-syslog: no
    logfile: ""
    val-log-level: 1
    num-threads: 1
    msg-cache-size: 0
    rrset-cache-size: 0
    key-cache-size: 0
    neg-cache-size: 0
    prefetch: no
    prefetch-key: no

    # Trust anchors for our zones
    trust-anchor: "test-valid-rsa.example. 300 IN DNSKEY 257 3 8 AwEAAYf/CS0D4eNpAdPsf02mxJ6J/bMeU/8cmFk7ljl/3kp1pSD0TtI7DGiilZJRXFue+JoDTz1EZjfWjjV+lgXAOTJEGq/QwJZtqvURpn2uZyGJrVd+qkcEqUgOw4NZAwCohb0f9beyj0+qSLZ2L6vpSpLB5nMPRj3t4zgpk42N88VCCvqAdmWVX6SswoP2xbCgEiwYR8gzZVHA06VdVYuBfLgCFD6J7E7mS/lizZHjzoFdw97IxKRzk9PUinjJOtbEcDD8DwjzjMoNEHry1/4pKILA6eEocsBV3EX2MlyMCm29Bbe9XHQGalOWxLyLmWaLsAUDlLt3Vthq+Sc7cS13OLM="
    trust-anchor: "test-valid-ecdsa.example. 300 IN DNSKEY 257 3 13 JWLq9zRMtAtl0dcyP7MiNJUzCvmIfwVdS5uxF26UPnr5xIgb+PhPRZn8+/99i0qLLjfaQ3YT8gPg2qtj4x//zg=="
    trust-anchor: "test-valid-ed25519.example. 300 IN DNSKEY 257 3 15 ltpY5ZPbfAJVHXBT6YkhoXaJHuqD/oLNwR4pDvwcWao="

    # Forward to auth server for our zones
    forward-zone:
        name: "test-valid-rsa.example."
        forward-addr: 172.31.0.10
    forward-zone:
        name: "test-valid-ecdsa.example."
        forward-addr: 172.31.0.10
    forward-zone:
        name: "test-valid-ed25519.example."
        forward-addr: 172.31.0.10
